# Generated by Django 5.0.2 on 2025-03-18 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_speaker_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='country',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
